# Generated by Django 5.2.14 on 2026-05-26 18:53
""" Migration file for the initial database schema. """

import django.db.models.deletion
import flags_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=False)),
                ("kill_switch", models.BooleanField(default=False)),
                (
                    "default_value",
                    models.JSONField(default=flags_django.models.default_false),
                ),
                ("rollout_percentage", models.PositiveSmallIntegerField(default=0)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flags",
                        to="flags_django.environment",
                    ),
                ),
            ],
            options={
                "ordering": ["environment__slug", "key"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=80)),
                ("actor", models.CharField(max_length=150)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="flags_django.environment",
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="flags_django.featureflag",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FlagRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("attribute", models.CharField(max_length=120)),
                ("operator", models.CharField(max_length=40)),
                ("value", models.JSONField()),
                ("result", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="flags_django.featureflag",
                    ),
                ),
            ],
            options={
                "ordering": ["flag", "order"],
            },
        ),
        migrations.CreateModel(
            name="SnapshotVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=0)),
                ("etag", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "environment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot_version",
                        to="flags_django.environment",
                    ),
                ),
            ],
            options={
                "ordering": ["environment__slug"],
            },
        ),
        migrations.AddConstraint(
            model_name="featureflag",
            constraint=models.UniqueConstraint(
                fields=("environment", "key"), name="unique_flag_key_per_environment"
            ),
        ),
        migrations.AddConstraint(
            model_name="featureflag",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rollout_percentage__gte", 0), ("rollout_percentage__lte", 100)
                ),
                name="flag_rollout_percentage_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="flagrule",
            constraint=models.UniqueConstraint(
                fields=("flag", "order"), name="unique_rule_order_per_flag"
            ),
        ),
    ]
